replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 80
  externalPort: 80
ingress:
  enabled: true
  basedomain: 4797c730d12144e5bdb0.eastus2.aksapp.io # replace with your own from the portal
