name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image: parrot

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build $image --file $image/Dockerfile --tag my-image-name:$(date +%s)
