name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    runs-on: [ubuntu-latest]
    env:
      image: parrot
     

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build $image --file $image/Dockerfile --tag my-image-name:$(date +%s)
